### ISSUE TITLE
Explanation of changes

### ISSUE THREAD

**Issue by Naatan** [mbarbon/perl-remote-debugging-client#1]
Hi there, I'm the lead dev for Komodo IDE. I just found out about this repository and just wanted to first and foremost say thank you for sharing your work with others! While I don't know exactly what your work entails I'm always happy to see people paying it forward, especially with more complicated code such as this.

That said, would you be able to explain a little bit of what you have done with this codebase? ie. what features have you added/removed, what were your motivations? I'd love to get a sense for what this adds over the functionality we offer.

Thank you :)

**Comment by mbarbon** [comment]
Hi,
first of all, I'm very happy I found the Komodo debugging helper, it saved me from a lot of work; I did not try to contribute my changes because I did not think they would be relevant to the use in Komodo.

My goal is having a debugger I can use with various editors, and for scripting (via https://github.com/mbarbon/dbgp-client). I started with the Komodo debugging helper because it was a working DBGp implementation, but I'm not using Komodo.

There are various set of changes:
- support for multi-process (specifically Plack + uWSGI) so the debugger opens a new DBGp connection on each request (see also https://github.com/mbarbon/plack-middleware-dbgp)
- performance improvements, for example 01a250f2c72c63871f0e4c60c7262785a5cb2dd0, 552843196cf4f08b56d3e3cfcf31b58786a34432, 08fe97ea1139650dfa2bd5e0b4638069407f283e
- Xdebug compatibility (because all other debuggers are written against Xdebug, not against the DBGp spec): 48cf3f123febef249a613ccb0a2db6fb73492c72, 4956fc0e79a295c08df940a385840765248137a1, df4f8811193e0c35ba96e7767a9c78835338b7bd, ec03772662f5a57ec582961accc6d3596abb75d7
- allow connecting over Unix-domain sockets (to avoid having an open port in a semi-shared environment)
- code cleanup (use strict, fbe6ba63f19d37714aaf7701f2a4072e09e89bf0, 8373985937300b92f5589eaff9373fa88878eaca)
- removed interact command (not in Xdebug, so there is no editor support, and I can get a better result using https://github.com/mbarbon/devel-repl-inprocess): d212d36d6f36bdd07660a6a374cb95fdd84a55c2
- added tests for most commands, and various fixes for bugs found during testing

The list of commits above is not exhaustive, I just picked some commits that I though were significant. See also the https://raw.githubusercontent.com/mbarbon/perl-remote-debugging-client/master/TODO).

Let me know if you need more detail on specific changes.
